[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ['migrations']

[tool.pytest.ini_options]
pythonpath = "."
minversion = 2.0
norecursedirs = ['.git', '.tox',  'requirements*']
python_files = ['test*.py']
markers = [
    'integration: integration tests'
]

[tool.blue]
extend-exclude = ['(migrations/)', '(src/use_cases/pdf_create.py)']

[tool.taskipy.tasks]
run = 'uvicorn asgi:app --reload'
test = "pytest --cov=src/routers -vv"
# pre_test = 'task lint'
post_test = 'coverage html'
lint = 'ruff check . && blue --check . --diff'
format = 'blue . && isort .'
type = 'mypy src --explicit-package-bases'

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"