"""alteracao_tabela_atletaavatar_multiplos_arquivos

Revision ID: 01c719e9a06c
Revises: cfef75d0e9c2
Create Date: 2025-08-06 19:11:54.111048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01c719e9a06c'
down_revision: Union[str, None] = 'cfef75d0e9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletaavatar', sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('atletaavatar', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('atletaavatar', sa.Column('controle_id', sa.Integer(), nullable=True))
    op.add_column('atletaavatar', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.alter_column('atletaavatar', 'atleta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'atletaavatar', 'historicocontrole', ['controle_id'], ['id'])
    op.create_foreign_key(None, 'atletaavatar', 'contrato', ['contrato_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletaavatar', type_='foreignkey')
    op.drop_constraint(None, 'atletaavatar', type_='foreignkey')
    op.alter_column('atletaavatar', 'atleta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('atletaavatar', 'contrato_id')
    op.drop_column('atletaavatar', 'controle_id')
    op.drop_column('atletaavatar', 'descricao')
    op.drop_column('atletaavatar', 'tipo')
    # ### end Alembic commands ###
