"""add_arquivo_url_to_contrato

Revision ID: 01e926082dbe
Revises: 01c719e9a06c
Create Date: 2026-04-04 19:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01e926082dbe'
down_revision: Union[str, None] = '01c719e9a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('arquivo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrato', 'arquivo_url')
    # ### end Alembic commands ###
