"""adicionar_clube_atual_no_historico_clube

Revision ID: 4a682a8325a5
Revises: 533ba57d2cf7
Create Date: 2024-06-11 22:21:11.305741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a682a8325a5'
down_revision: Union[str, None] = '533ba57d2cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicoclube', sa.Column('clube_atual', sa.Boolean(), nullable=False))
    op.alter_column('historicoclube', 'data_fim',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historicoclube', 'data_fim',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('historicoclube', 'clube_atual')
    # ### end Alembic commands ###
