"""alterar_data_retorno_historico_lesao_para_null

Revision ID: 533ba57d2cf7
Revises: c722f0a5bff3
Create Date: 2024-06-11 11:50:08.452460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533ba57d2cf7'
down_revision: Union[str, None] = 'c722f0a5bff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historicolesao', 'data_retorno',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historicolesao', 'data_retorno',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
