"""move_arquivo_url_from_contrato_to_contratoversao

Revision ID: 9edd1fcaf8fe
Revises: 01e926082dbe
Create Date: 2026-04-05 00:29:27.355263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9edd1fcaf8fe'
down_revision: Union[str, None] = '01e926082dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrato', 'arquivo_url')
    op.add_column('contratoversao', sa.Column('arquivo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratoversao', 'arquivo_url')
    op.add_column('contrato', sa.Column('arquivo_url', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
