"""create_table_atleta_link

Revision ID: cfef75d0e9c2
Revises: d1ea98482c76
Create Date: 2025-05-18 20:42:13.139068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfef75d0e9c2'
down_revision: Union[str, None] = 'd1ea98482c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletalink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('atletaposicao', 'preferencia',
    #            existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
    #            type_=sqlmodel.sql.sqltypes.AutoString(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletaposicao', 'preferencia',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_table('atletalink')
    # ### end Alembic commands ###
